# Importing libraries and the dataset

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

from sklearn.linear_model import Ridge, Lasso, LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [2]:
quiz_data = pd.read_csv('energydata_complete.csv')
quiz_data.head()

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,2016-01-11 17:00:00,60,30,19.89,47.596667,19.2,44.790000,19.79,44.730000,19.000000,...,17.033333,45.53,6.600000,733.5,92.0,7.000000,63.000000,5.3,13.275433,13.275433
1,2016-01-11 17:10:00,60,30,19.89,46.693333,19.2,44.722500,19.79,44.790000,19.000000,...,17.066667,45.56,6.483333,733.6,92.0,6.666667,59.166667,5.2,18.606195,18.606195
2,2016-01-11 17:20:00,50,30,19.89,46.300000,19.2,44.626667,19.79,44.933333,18.926667,...,17.000000,45.50,6.366667,733.7,92.0,6.333333,55.333333,5.1,28.642668,28.642668
3,2016-01-11 17:30:00,50,40,19.89,46.066667,19.2,44.590000,19.79,45.000000,18.890000,...,17.000000,45.40,6.250000,733.8,92.0,6.000000,51.500000,5.0,45.410389,45.410389
4,2016-01-11 17:40:00,60,40,19.89,46.333333,19.2,44.530000,19.79,45.000000,18.890000,...,17.000000,45.40,6.133333,733.9,92.0,5.666667,47.666667,4.9,10.084097,10.084097

In [3]:
quiz_data.drop(['lights'], axis=1,inplace=True)
quiz_data.drop(['date'], axis=1, inplace=True)

**Preprocessing**

In [4]:
scaler = MinMaxScaler()
normalized_features = pd.DataFrame(scaler.fit_transform(quiz_data), columns=quiz_data.columns)

features = normalized_features.drop(['Appliances'], axis=1)
target = normalized_features['Appliances']

In [5]:
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size = 0.3, random_state = 42)
X_train.head()

,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,RH_5,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
9129,0.497360,0.236767,0.122850,0.565939,0.373878,0.303474,0.476577,0.264760,0.408027,0.159533,...,0.475893,0.376380,0.168810,0.862791,0.776316,0.142857,0.984615,0.192308,0.724554,0.724554
2453,0.286167,0.482616,0.188999,0.669978,0.217957,0.735317,0.270270,0.691421,0.178691,0.333576,...,0.240375,0.703504,0.262594,0.836434,0.807018,0.142857,0.600000,0.342383,0.864041,0.864041
9152,0.422386,0.230529,0.057427,0.606430,0.373878,0.338059,0.414414,0.236449,0.378404,0.151639,...,0.468262,0.409803,0.110397,0.853488,0.859649,0.095238,0.917949,0.158371,0.499502,0.499502
12694,0.560718,0.446840,0.280834,0.704002,0.514290,0.515189,0.540541,0.486556,0.509317,0.424604,...,0.561915,0.340784,0.444802,0.559690,0.750000,0.119048,0.384615,0.558069,0.323173,0.323173
16952,0.835269,0.422071,1.000000,0.318493,0.745383,0.459106,0.900901,0.516432,0.748845,0.455819,...,0.854318,0.633278,0.849946,0.530233,0.355263,0.142857,0.600000,0.787330,0.341060,0.341060

In [6]:
print('Question 12\n')

Xtrain = X_train[['T2']]
Ytrain = X_train[['T6']]

Xtest = X_test[['T2']]
Ytest = X_test[['T6']]

model = LinearRegression()
model.fit(Xtrain, Ytrain)
predict = model.predict(Xtest)

r2_value = round(r2_score(Ytest, predict), 2)
print('R2 Score =', r2_value)

Question 12

R2 Score = 0.64

In [7]:
#Linear Regression Model for 13-17

linear_regression = LinearRegression()
linear_regression.fit(X_train, y_train)
y_predicted = linear_regression.predict(X_test)

In [8]:
print('Question 13\n')

mae_value = round(mean_absolute_error(y_test, y_predicted), 2)
print('MAE =', mae_value)

Question 13

MAE = 0.05

In [9]:
print('Question 14\n')

rss_value = round(np.sum(np.square(y_test - y_predicted)), 2)
print('RSS =', rss_value)

Question 14

RSS = 45.35

In [10]:
print('Question 15\n')

rmse_value = round(np.sqrt(mean_squared_error(y_test, y_predicted)), 3)
print('RMSE =', rmse_value)

Question 15

RMSE = 0.088

In [11]:
print('Question 16\n')

r2_value = r2_score(y_test, y_predicted)
print('Coefficient of Determination =', round(r2_value, 2))

Question 16

Coefficient of Determination = 0.15

In [12]:
print('Question 17\n')

def get_weights(model, feature, column_name):
  weights = pd.Series(model.coef_, feature.columns).sort_values()
  weights_dataframe = pd.DataFrame(weights).reset_index()
  weights_dataframe.columns = ['Features', column_name]
  weights_dataframe[column_name].round(3)
  return weights_dataframe

linear_weights = get_weights(linear_regression, X_train, 'Linear_weight')
print('Lowest & Highest:')
linear_weights.iloc[[0, -1], :]

Question 17

Lowest & Highest:

   Features  Linear_weight
0      RH_2      -0.456698
25     RH_1       0.553547

In [13]:
print('Question 18\n')

ridge = Ridge()
ridge.fit(X_train, y_train)
predicted = ridge.predict(X_test)

ridge_rmse_value = round(np.sqrt(mean_squared_error(y_test, predicted)), 3)

print(f'The RMSE score for the rigde model with default aplha value when evaluated on the test set is: {ridge_rmse_value}')


ridge_reg = Ridge(alpha=0.4)
ridge_reg.fit(X_train, y_train)
new_predicted = ridge_reg.predict(X_test)

ridge_rmse_new = round(np.sqrt(mean_squared_error(y_test, new_predicted)), 3)

print(f'The RMSE score for the rigde model with new aplha value when evaluated on the test set is: {ridge_rmse_new}')

Question 18

The RMSE score for the rigde model with default aplha value when evaluated on the test set is: 0.088
The RMSE score for the rigde model with new aplha value when evaluated on the test set is: 0.088

In [14]:
print('Question 19\n')

lasso_regression = Lasso(alpha=0.001)
lasso_regression.fit(X_train, y_train)
lasso_predicted = lasso_regression.predict(X_test)

def get_weights(model, feature, column_name):
  weights = pd.Series(model.coef_, feature.columns).sort_values()
  weights_dataframe = pd.DataFrame(weights).reset_index()
  weights_dataframe.columns = ['Features', column_name]
  weights_dataframe[column_name].round(3)
  return weights_dataframe

lasso_weights = get_weights(lasso_regression, X_train, 'Lasso_weight')
non_zero_weights = lasso_weights[lasso_weights['Lasso_weight'] != 0]

print('No of features =', len(non_zero_weights))

Question 19

No of features = 4

In [15]:
print('Question 20\n')

new_rmse_value = round(np.sqrt(mean_squared_error(y_test, lasso_predicted)), 3)
print('New RMSE =', new_rmse_value)

Question 20

New RMSE = 0.094